### ISSUE TITLE
[Epic] Test Coverage should be 100%

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#350]
- [x] BlockManager/ClaimBlockReward()
- [x] finalize dispute should not work if medians = 0
- [x] BlockManager/ getProposedBlock, getBlockMedians, getProposedBlockMedians[
- [x] test cases for updateCollection
- [x] StakeManager / withdraw / https://github.com/razor-network/contracts/blob/8a27a6878c3f6ebd115b8c298b725ef46b438a95/contracts/Core/StakeManager.sol#L184
- [x] StakeManager / resetLock / https://github.com/razor-network/contracts/blob/8a27a6878c3f6ebd115b8c298b725ef46b438a95/contracts/Core/StakeManager.sol#L258
- [x] StakeManager / withdraw / https://github.com/razor-network/contracts/blob/8a27a6878c3f6ebd115b8c298b725ef46b438a95/contracts/Core/StakeManager.sol#L187
- [x] check finalizeDispute should not work if total Influence Reward does not match
- [x] Initializable/ initializer (Write test case to check modifier initializer in Initializable.sol
- [x] StateManager / checkDisputeorConfirmState, notCommitState
- [x] #437
- [x] Add test with different bigInflucnerId passed in propose, preference should be given to correct ones, even if iteration for propose with incorrect bigInfluencerId is lesser
Ref : https://github.com/razor-network/contracts/issues/414#issuecomment-918263520

**Comment by SkandaBhat** [comment]
@GauravJain9 what is the status on this? Why is `BlockManager/ insertAppropriately` not closed yet?

**Comment by GauravJain9** [comment]
> @GauravJain9 what is the status on this? Why is `BlockManager/ insertAppropriately` not closed yet?

Actually inside this function the if block which was thought of as redundant is no more redundant and it is useful so once after testing that part (which is itself the 12th task)  both task 11 & 12 can be closed.
